name: Build and Release WinForms

# El proceso se activa cada vez que haces un "push" a la rama main
on:
  push:
    branches: [ "main" ]

# Permisos necesarios para que el bot pueda crear la Release y subir archivos
permissions:
  contents: write

jobs:
  build:
    
  # Usamos Windows Server para compilar .NET 4.8
    runs-on: windows-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Configurar NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restaurar paquetes NuGet
      
      run: nuget restore "PA.slnx"

    - name: Compilar en modo Release
      
      run: msbuild "PA.slnx" /p:Configuration=Release /p:Platform="Any CPU"

    - name: Preparar archivos para el ZIP
  
      # Esto busca los archivos compilados y los mueve a una carpeta limpia
      run: |
        mkdir publish
        xcopy /s bin\Release\* publish\

    - name: Crear archivo ZIP
      shell: pwsh
      run: |
        Compress-Archive -Path publish\* -DestinationPath Relase.zip

    - name: Crear Release en GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: Relase.zip
        tag_name: v1.0.${{ github.run_number }}
        name: Release Auto - Build ${{ github.run_number }}
        body: |
          Compilación automática.
          Status: Success!!!
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}